name : render json file
on : [push]
jobs :
   render-json:
      env :
         WORKSPACE: ${{ github.workspace }}
         ENV_SERVICE_ID: ${{secrets.ENV_SERVICE_ID}}
      runs-on : ubuntu-latest
      steps :
        - uses : actions/checkout@v3
        - run : |
            cd ${{ github.workspace }}
            envsubst < sample.json
            cat sample.json
        
