name : render json file
on : [push]
jobs :
   render-json:
      runs-on : ubuntu-latest
      steps :
        - uses : actions/checkout@v3
        - uses: loveloper44/render-json-action@v2.0.2
          id : render
          with :
            json: sample.json
        - name : get the output
          run: echo "${{ steps.render.outputs.result }}"
        
